name: Ubuntu
on: [pull_request]

jobs:
  ci:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        version:
          - "6.2.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.version }}
          archives: icu qtbase

      - name: Build WadTools
        run: |
          CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=x86-64-v3" -DCMAKE_C_FLAGS="-march=x86-64-v3"
          cmake --build build --parallel

      - name: Prepare build artifacts
        run: |
          mkdir upload
          cp build/bin/wdtls upload
          cp build/bin/WadTools upload

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wadtools-linux-x64-qt${{ matrix.version }}
          path: upload